### ISSUE TITLE
The running results are inconsistent with the paper

### ISSUE THREAD

**Issue by 0SliverBullet** [jmanzolli/E-VRPTW#1]
1. The distance calculation should not only retain one decimal place, as there is a large accuracy error.
2. The cplex code does not optimize the number of vehicles first and then optimize the total distance.
3. The recharging station does not have a set copy, which is inconsistent with "a set of dummy vertices generated to permit several visits to each vertex in the set F of recharging stations" in the paper.

**Comment by jmanzolli** [comment]
Hello, this code was done a long time ago for a different purpose, and it is **based** on the paper of Schneider et al (2014). Do you like to contribute and improve the code? Be my guest! I can later merge your insights.

**Comment by 0SliverBullet** [comment]
Thanks for your quick reply! I am delighted to contribute and improve the code.

**Comment by jmanzolli** [comment]
Great! Be free to improve the code, thank you!
